plugins {
    id 'java'
    id 'com.github.johnrengelman.shadow' version '8.1.1'
}

group = 'dev.adminpunish'
version = '1.1.0'

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

repositories {
    mavenCentral()
    maven { url = 'https://hub.spigotmc.org/nexus/content/repositories/snapshots/' }
    maven { url = 'https://oss.sonatype.org/content/repositories/snapshots' }
}

dependencies {
    compileOnly 'org.spigotmc:spigot-api:1.21.1-R0.1-SNAPSHOT'
    implementation 'com.google.code.gson:gson:2.10.1'
}

shadowJar {
    relocate 'com.google.gson', 'dev.adminpunish.libs.gson'
    archiveFileName = "Sk3llyZ1psPunishments-${version}.jar"
    archiveClassifier = ''
}

build.dependsOn shadowJar
